# 项目信息自动填单配置文件
# 如果不需要自定义路径，可以留空或者删除对应配置项，将使用默认路径
[paths]
# 文件模板目录，默认值：文件模板
source_dir = 文件模板
# 标准化模板目录，默认值：标准化模板
template_dir = 标准化模板
# 输出文件目录，默认值：输出文件
output_dir = 输出文件
# 项目信息配置文件路径，默认值：项目信息.txt
project_info_file = 项目信息.txt
